// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GhostMQServiceClient is the client API for GhostMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GhostMQServiceClient interface {
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*QueueInfo, error)
	PushMessage(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error)
	PopMessage(ctx context.Context, in *PopMessageRequest, opts ...grpc.CallOption) (*Message, error)
	AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageResponse, error)
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type ghostMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGhostMQServiceClient(cc grpc.ClientConnInterface) GhostMQServiceClient {
	return &ghostMQServiceClient{cc}
}

func (c *ghostMQServiceClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*QueueInfo, error) {
	out := new(QueueInfo)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) PushMessage(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error) {
	out := new(PushMessageResponse)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/PushMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) PopMessage(ctx context.Context, in *PopMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/PopMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) AckMessage(ctx context.Context, in *AckMessageRequest, opts ...grpc.CallOption) (*AckMessageResponse, error) {
	out := new(AckMessageResponse)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/AckMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/ListQueues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostMQServiceClient) Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/ghostmq.v1.GhostMQService/Metrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GhostMQServiceServer is the server API for GhostMQService service.
// All implementations must embed UnimplementedGhostMQServiceServer
// for forward compatibility
type GhostMQServiceServer interface {
	CreateQueue(context.Context, *CreateQueueRequest) (*QueueInfo, error)
	PushMessage(context.Context, *PushMessageRequest) (*PushMessageResponse, error)
	PopMessage(context.Context, *PopMessageRequest) (*Message, error)
	AckMessage(context.Context, *AckMessageRequest) (*AckMessageResponse, error)
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedGhostMQServiceServer()
}

// UnimplementedGhostMQServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGhostMQServiceServer struct {
}

func (UnimplementedGhostMQServiceServer) CreateQueue(context.Context, *CreateQueueRequest) (*QueueInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedGhostMQServiceServer) PushMessage(context.Context, *PushMessageRequest) (*PushMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessage not implemented")
}
func (UnimplementedGhostMQServiceServer) PopMessage(context.Context, *PopMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopMessage not implemented")
}
func (UnimplementedGhostMQServiceServer) AckMessage(context.Context, *AckMessageRequest) (*AckMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckMessage not implemented")
}
func (UnimplementedGhostMQServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedGhostMQServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGhostMQServiceServer) Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedGhostMQServiceServer) mustEmbedUnimplementedGhostMQServiceServer() {}

// UnsafeGhostMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GhostMQServiceServer will
// result in compilation errors.
type UnsafeGhostMQServiceServer interface {
	mustEmbedUnimplementedGhostMQServiceServer()
}

func RegisterGhostMQServiceServer(s grpc.ServiceRegistrar, srv GhostMQServiceServer) {
	s.RegisterService(&GhostMQService_ServiceDesc, srv)
}

func _GhostMQService_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_PushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).PushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/PushMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).PushMessage(ctx, req.(*PushMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_PopMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).PopMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/PopMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).PopMessage(ctx, req.(*PopMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/AckMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).AckMessage(ctx, req.(*AckMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/ListQueues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostMQService_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostMQServiceServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghostmq.v1.GhostMQService/Metrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostMQServiceServer).Metrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GhostMQService_ServiceDesc is the grpc.ServiceDesc for GhostMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GhostMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghostmq.v1.GhostMQService",
	HandlerType: (*GhostMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _GhostMQService_CreateQueue_Handler,
		},
		{
			MethodName: "PushMessage",
			Handler:    _GhostMQService_PushMessage_Handler,
		},
		{
			MethodName: "PopMessage",
			Handler:    _GhostMQService_PopMessage_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _GhostMQService_AckMessage_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _GhostMQService_ListQueues_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _GhostMQService_Health_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _GhostMQService_Metrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpcserver/ghostmq.proto",
}
